### ISSUE TITLE
依赖包报错

### ISSUE THREAD

**Issue by NooooBuG** [TingsongYu/PyTorch_Tutorial#42]
Traceback (most recent call last):
  File "E:/王庆洲毕设/PyTorch_Tutorial-master/Code/main_training/main.py", line 38, in <module>
    writer = SummaryWriter(log_dir=log_dir)
  File "D:\MiniConda3\envs\PyTorch_Tutorial-master\lib\site-packages\tensorboardX\writer.py", line 292, in __init__
    from caffe2.python import workspace  # workaround for pytorch/issue#10249
  File "D:\MiniConda3\envs\PyTorch_Tutorial-master\lib\site-packages\caffe2\python\__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
  File "D:\MiniConda3\envs\PyTorch_Tutorial-master\lib\site-packages\caffe2\proto\__init__.py", line 11, in <module>
    from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
  File "D:\MiniConda3\envs\PyTorch_Tutorial-master\lib\site-packages\caffe2\proto\caffe2_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by NooooBuG** [comment]
writer = SummaryWriter(log_dir=log_dir)
此处报错

**Comment by NooooBuG** [comment]
请问requirement.txt是否应该更新了

**Comment by NooooBuG** [comment]
已解决
